// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    int32
}

type Series struct {
	ID          int32
	Title       string
	Description sql.NullString
	UploadedAt  time.Time
	UserID      int32
}

type SeriesEpisode struct {
	ID         int32
	Title      string
	Season     int32
	Episode    int32
	UploadedAt time.Time
	UploadedBy int32
	SeriesID   int32
}

type User struct {
	ID             int32
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
