// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
)

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (email, hashed_password, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, email, hashed_password, created_at, updated_at
`

type RegisterUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, registerUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
